$(".more1").click(function(){
	$(".hide1").slideToggle('slow')
});
$(".more2").click(function(){
	$(".hide2").slideToggle('slow')
});
$(".more3").click(function(){
	$(".hide3").slideToggle('slow')
});